import { getPool } from './postgres';

const MIGRATIONS: { name: string; sql: string }[] = [
  {
    name: '001_create_seo_tables',
    sql: `
      -- Migration tracking
      CREATE TABLE IF NOT EXISTS seo_migrations (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        applied_at TIMESTAMPTZ DEFAULT NOW()
      );

      -- Per-site SEO configuration
      CREATE TABLE IF NOT EXISTS seo_site_config (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        site_id TEXT NOT NULL,
        env_id TEXT NOT NULL,
        semrush_domain TEXT,
        enabled_features JSONB NOT NULL DEFAULT '{"title_optimization":true,"meta_description":true,"internal_linking":true,"schema_markup":false,"redirect_management":false}',
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW(),
        UNIQUE(site_id, env_id)
      );

      -- WP-CLI crawl snapshots
      CREATE TABLE IF NOT EXISTS seo_crawl_snapshots (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        site_id TEXT NOT NULL,
        env_id TEXT NOT NULL,
        crawl_data JSONB NOT NULL DEFAULT '{}',
        post_count INTEGER DEFAULT 0,
        page_count INTEGER DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
        error TEXT,
        started_at TIMESTAMPTZ DEFAULT NOW(),
        completed_at TIMESTAMPTZ
      );

      -- SEMrush keyword snapshots
      CREATE TABLE IF NOT EXISTS seo_semrush_snapshots (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        site_id TEXT NOT NULL,
        env_id TEXT NOT NULL,
        domain TEXT NOT NULL,
        keyword_data JSONB NOT NULL DEFAULT '[]',
        organic_traffic INTEGER,
        fetched_at TIMESTAMPTZ DEFAULT NOW()
      );

      -- SEO plans generated by Claude
      CREATE TABLE IF NOT EXISTS seo_plans (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        site_id TEXT NOT NULL,
        env_id TEXT NOT NULL,
        crawl_snapshot_id UUID REFERENCES seo_crawl_snapshots(id),
        semrush_snapshot_id UUID REFERENCES seo_semrush_snapshots(id),
        model_used TEXT NOT NULL,
        prompt_tokens INTEGER DEFAULT 0,
        completion_tokens INTEGER DEFAULT 0,
        strategy_summary TEXT NOT NULL DEFAULT '',
        keyword_clusters JSONB NOT NULL DEFAULT '[]',
        status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'executing', 'executed', 'rolled_back')),
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );

      -- Individual changes within a plan
      CREATE TABLE IF NOT EXISTS seo_plan_changes (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        plan_id UUID NOT NULL REFERENCES seo_plans(id) ON DELETE CASCADE,
        post_id INTEGER,
        change_type TEXT NOT NULL,
        field_name TEXT NOT NULL,
        old_value TEXT,
        new_value TEXT NOT NULL,
        reasoning TEXT NOT NULL DEFAULT '',
        priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
        status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'skipped', 'executed', 'failed', 'rolled_back')),
        execution_order INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );

      -- Pre-execution content backups
      CREATE TABLE IF NOT EXISTS seo_content_backups (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        change_id UUID NOT NULL REFERENCES seo_plan_changes(id) ON DELETE CASCADE,
        plan_id UUID NOT NULL REFERENCES seo_plans(id) ON DELETE CASCADE,
        post_id INTEGER,
        field_name TEXT NOT NULL,
        original_value TEXT NOT NULL,
        backed_up_at TIMESTAMPTZ DEFAULT NOW()
      );

      -- SSH command execution log
      CREATE TABLE IF NOT EXISTS seo_execution_log (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        plan_id UUID NOT NULL REFERENCES seo_plans(id) ON DELETE CASCADE,
        change_id UUID REFERENCES seo_plan_changes(id) ON DELETE SET NULL,
        command TEXT NOT NULL,
        stdout TEXT NOT NULL DEFAULT '',
        stderr TEXT NOT NULL DEFAULT '',
        exit_code INTEGER NOT NULL,
        duration_ms INTEGER NOT NULL DEFAULT 0,
        executed_at TIMESTAMPTZ DEFAULT NOW()
      );

      -- Ranking snapshots for before/after comparison
      CREATE TABLE IF NOT EXISTS seo_ranking_snapshots (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        site_id TEXT NOT NULL,
        env_id TEXT NOT NULL,
        plan_id UUID REFERENCES seo_plans(id) ON DELETE SET NULL,
        snapshot_type TEXT NOT NULL CHECK (snapshot_type IN ('before', 'after')),
        rankings JSONB NOT NULL DEFAULT '[]',
        captured_at TIMESTAMPTZ DEFAULT NOW()
      );

      -- Review reports
      CREATE TABLE IF NOT EXISTS seo_reports (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        site_id TEXT NOT NULL,
        env_id TEXT NOT NULL,
        plan_id UUID REFERENCES seo_plans(id) ON DELETE SET NULL,
        report_type TEXT NOT NULL CHECK (report_type IN ('plan_review', 'execution_review', 'ranking_review')),
        content TEXT NOT NULL DEFAULT '',
        model_used TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      -- Indexes
      CREATE INDEX IF NOT EXISTS idx_crawl_snapshots_site ON seo_crawl_snapshots(site_id, env_id);
      CREATE INDEX IF NOT EXISTS idx_semrush_snapshots_site ON seo_semrush_snapshots(site_id, env_id);
      CREATE INDEX IF NOT EXISTS idx_plans_site ON seo_plans(site_id, env_id);
      CREATE INDEX IF NOT EXISTS idx_plan_changes_plan ON seo_plan_changes(plan_id);
      CREATE INDEX IF NOT EXISTS idx_content_backups_change ON seo_content_backups(change_id);
      CREATE INDEX IF NOT EXISTS idx_execution_log_plan ON seo_execution_log(plan_id);
      CREATE INDEX IF NOT EXISTS idx_ranking_snapshots_site ON seo_ranking_snapshots(site_id, env_id);
      CREATE INDEX IF NOT EXISTS idx_reports_site ON seo_reports(site_id, env_id);
    `,
  },
];

export async function runMigrations(): Promise<void> {
  const pool = getPool();
  const client = await pool.connect();

  try {
    // Ensure migrations table exists
    await client.query(`
      CREATE TABLE IF NOT EXISTS seo_migrations (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        applied_at TIMESTAMPTZ DEFAULT NOW()
      )
    `);

    // Get applied migrations
    const applied = await client.query('SELECT name FROM seo_migrations');
    const appliedNames = new Set(applied.rows.map((r) => r.name));

    for (const migration of MIGRATIONS) {
      if (appliedNames.has(migration.name)) {
        console.log(`[SEO Migration] Skipping ${migration.name} (already applied)`);
        continue;
      }

      console.log(`[SEO Migration] Applying ${migration.name}...`);
      await client.query('BEGIN');
      try {
        await client.query(migration.sql);
        await client.query('INSERT INTO seo_migrations (name) VALUES ($1)', [migration.name]);
        await client.query('COMMIT');
        console.log(`[SEO Migration] Applied ${migration.name}`);
      } catch (err) {
        await client.query('ROLLBACK');
        throw err;
      }
    }

    console.log('[SEO Migration] All migrations complete');
  } finally {
    client.release();
  }
}
